name: Export Godot APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Android APK via Godot
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: IVORY-APK
          path: /github/workspace/build/
          
